# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  backend:
    cmds:
      - go tool air
  frontend:
    cmds:
      - cd ui && npm run dev
